### ISSUE TITLE
Paper Voting

### ISSUE THREAD

**Issue by jaderabbit** [getkalido/kalido-ml-reading-group#1]
_In this issue you can either_:

- Add papers that you think are interesting to read and discuss (please stick to the format).
- Vote: should be done using :+1: on comments

Example: https://github.com/hadyelsahar/awesome-reading-group/issues/1

**Comment by raulincze** [comment]
Title: **Knowledge distillation for semi-supervised domain adaptation**
Link: https://arxiv.org/pdf/1908.07355.pdf

A paper that's applied on images but that might offer some insights into how to easily adapt to distribution shifts / changes as we tackle more and more clients and have to match a big variety of skills or searches / provides.

**Comment by raulincze** [comment]
Title: **Teaching Semi-Supervised Classifier via Generalized Distillation**
Link: https://www.ijcai.org/Proceedings/2018/0298.pdf

Describes the concept of "generalized knowledge distillation" where the teacher network uses a "privileged" set of features to "teach" the learner things. I was thinking that we might be able to use such an approach instead of having "one model to rule them all" (multiple tasks/heads), with the teacher network having access to privileged info such as co-occurrences of skills or scraped skill definitions.

**Comment by raulincze** [comment]
Changing the format, so will close this for now. Might resurrect my posts into their own issues.
